[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aoc-utils"
version = "2024.0.dev1"
requires-python = ">=3.12"
dependencies = [
    "portion>=2.4.1",
]
